[theme]
base = "light"
primaryColor = "#1769e0"
backgroundColor = "#f7f9fc"
secondaryBackgroundColor = "#eef4ff"
textColor = "#17233c"
font = "sans serif"

[server]
headless = true
runOnSave = true

[browser]
gatherUsageStats = false
